= Mule Agent Modules

Includes Mule Agent extensions. For more information about how extending Mule Agent please check link:http://mulesoft.github.io/mule-agent/#_how_to_extend_mule_agent[documentation].

= Monitoring Publishers

== Adding your JMX Monitoring Publisher

To add your own publisher please refer to link:http://mulesoft.github.io/mule-agent/#_adding_new_jmx_publisher[Agent documentation]

== Zabbix Publisher

The Zabbix publisher supports version 2.0 of the Zabbix Sender protocol.
To receive the metrics published by the Zabbix Publisher the source of the metrics
must be configured in Zabbix as *zabbix_trapper*.

=== Configurable Fields


|===
|Field | Data Type |Description |Default Value

|host
|String
|Represents the host name for the Mule instance as defined in the Zabbix server.
|"com.mulesoft.agent"

|zabbixServer
|String
|Represents the location of the Zabbix server to which the metrics should be published.
|"0.0.0.0"

|zabbixPort
|Integer
|Represents the port on which the Zabbix server is listening.
|10051

|===

=== Configuration Example

[source,yaml]
.Zabbix Configuration
....
---
mule.agent.zabbix.jmx.internal.handler:
  host: com.mulesoft.agent
  zabbixServer: 54.166.172.53
  zabbixPort: 10051
....


== Nagios Publisher

The Nagios publisher works by sending passive checks to Nagios via the NSCA add-on.
For the publisher to work the add-on must be installed and configured.

=== Configurable Fields

|===
|Field | Data Type |Description |Default Value

|host
|String
|Represents the host name for the Mule instance as defined in the Nagios server.
|"com.mulesoft.agent"

|nagiosServer
|String
|Represents the location of the Nagios server to which the metrics should be published.
|"0.0.0.0"

|nagiosPort
|Integer
|Represents the port on which the Nagios server is listening.
|5667

|encryptionMethod
|String
|Represents the encryption method to be used for transmiting the metrics via the NSCA protocol.
|"XOR"

|password
|String
|Represents the password the host if one is configured. This field is optional.
|No default value

|===


*Default Value*: No default value

=== Configuration Example

[source,yaml]
.Nagios Configuration
....
---
mule.agent.nagios.jmx.internal.handler:
  host: com.mulesoft.agent
  nagiosServer: 54.166.172.53
  nagiosPort: 5667
  encryptionMethod: XOR
  password myPassword
....


== Graphite Publisher

The Graphite publisher works by sending metrics to the Graphite server. For the
publisher to work correctly the data retention for the metrics to be pushed needs
to be correctly set up in Graphite.

=== Configurable Fields


|===
|Field | Data Type |Description |Default Value

|metricPrefix
|String
|Represents the prefix configured in Graphite for the metrics coming from this Mule instance.
This rules for accepting metrics with this prefix must be correctly configured in Graphite for the publisher to work correctly.
|"mule"

|graphiteServer
|String
|Represents the location of the Graphite's Carbon server to which the metrics should be published.
|"0.0.0.0"

|graphitePort
|Integer
|Represents the port on which Graphite's Carbon server is listening.
|2003


|===



=== Configuration Example

[source,yaml]
.Graphite Configuration
....
---
mule.agent.graphite.jmx.internal.handler:
  metricPrefix: mule
  graphiteServer: 54.166.172.53
  graphitePort: 2003
....


== CloudWatch Publisher

The CloudWatch publisher sends metrics to the CloudWatch account corresponding to
the credentials set up in the configurable fields. The namespace used for the publisher
should be unique to each Mule intance to avoid receiving metrics from different Mule
instances only to have them grouped together.

=== Configurable Fields

|===
|Field | Data Type |Description |Default Value

|namespace
|String
|Represents the namespace for the metrics for this Mule instance as defined in CloudWatch.
|"com.mulesoft.agent"

|accessKey
|String
|Represents the CloudWatch access key.
|"missingAccessKey"

|secretKey
|String
|Represents the CloudWatch secret key.
|"missingSecretKey"

|===


=== Configuration Example

[source,yaml]
.CloudWatch Configuration
....
---
cloudwatch.agent.monitor.publisher:
  namespace: com.mulesoft.agent
  accessKey: missingAccessKey
  secretKey: missingSecretKey
....







