= Splunk Internal Handler

The Splunk Internal handler will store all the Event Notifications produced from the
Mule Runtime flows into a Splunk instance.

== Splunk Instance Configuration

In order to achieve this you must configure a new source type on your Splunk instance that will have the correct configuration
to parse the Event Notifications sent from the Mule Runtime.
To do this you have to append to $SPLUNK_HOME/opt/splunk/etc/system/local/props.conf
file the following source type (create the file if it doesn't exists), and restart the Splunk instance:

....
[mule]
TRUNCATE = 0
LINE_BREAKER = ([\r\n]+)
SHOULD_LINEMERGE = false
INDEXED_EXTRACTIONS = JSON
KV_MODE = JSON
category = Mule Splunk Integration
description = Mule Agent event information
....

=== Configurable Fields

|===
|Field|Data Type|Description|Type|Default Value

|user
|String
|Username to connect to Splunk.
|Required
|

|pass
|String
|The password of the user to connect to Splunk.
|Required
|

|host
|String
|IP or hostname of the server where Splunk is running.
|Required
|

|port
|int
|Splunk management port.
|Optional
|8089

|scheme
|String
|Scheme of connection to the Splunk management port. Possible values: http, https.
|Optional
|https

|sslSecurityProtocol
|String
|SSL Security Protocol to use in the https connection. Possible values: TLSv1_2, TLSv1_1, TLSv1, SSLv3.
|Optional
|TLSv1_2

|splunkIndexName
|String
|Splunk index name where all the events will be sent. If the user has the rights,
and the index doesn't exists, then the internal handler will create it.
|Optional
|main

|splunkSource
|String
|The source used on the events sent to Splunk.
|Optional
|mule

|splunkSourceType
|String
|The sourcetype used on the events sent to Splunk.
|Optional
|mule

|dateFormatPattern
|String
|Date format used to format the timestamp.
|Optional
|yyyy-MM-dd'T'HH:mm:ssSZ

|===

=== Configuration Example

[source,yaml]
.Splunk Internal Handler minimum Configuration
....
---
  mule.agent.tracking.handler.splunk:
    host: 192.168.61.131
    user: admin
    pass: test
....