= DB Internal Handler

The DB Internal handler will store all the Event Notifications produced from the
Mule ESB flows in a configurable database.
You have to copy your JDBC .jar driver to the {MULE_HOME}/plugins/mule-agent-plugin/lib,
so the mule agent can load it to the classpath.

=== Configurable Fields


|===
|Field|Data Type|Description|Type|Default Value

|driver
|String
|Represents the JDBC driver to use to communicate with the database server.
|Required
|

|jdbcUrl
|String
|Represents the JDBC url to the database server.
|Required
|

|user
|String
|The username to connect to the database server.
|Required
|

|pass
|String
|The password to connect to the database server.
|Required
|

|eventsTable
|String
|Represents the name of the table in which the agent will store the events.
|Optional
|MULE_EVENTS

|annotationsTable
|String
|Represents the name of the table in which the agent will store the annotations associated to the main event.
|Optional
|MULE_EVENTS_ANNOTATIONS

|businessTable
|String
|Represents the name of the table in which the agent will store the custom business events associated to the main event.
|Optional
|MULE_EVENTS_BUSINESS

|===

=== Proposed Table Schema to Store the Events

As an example we show the configuration for storing the events on a MySQL database.

[source,sql]
....
CREATE TABLE MULE_EVENTS (
    id CHAR(36) NOT NULL,
 	action VARCHAR(500) NULL,
 	application VARCHAR(500) NULL,
 	mule_message LONGTEXT NULL,
 	mule_message_id VARCHAR(36) NULL,
 	notification_type VARCHAR(500) NULL,
 	path VARCHAR(500) NULL,
 	resource_identifier VARCHAR(500) NULL,
 	timestamp BIGINT NULL,
 	source TEXT NULL,
 	PRIMARY KEY (id)
);

CREATE TABLE MULE_EVENTS_ANNOTATIONS (
  id CHAR(36) NOT NULL,
  event_id CHAR(36) NOT NULL,
  annotation_type VARCHAR(100) NULL,
  annotation_value VARCHAR(255) NULL,
  PRIMARY KEY (id),
  KEY FK_MULE_EVENTS_ANNOTATIONS_MULE_EVENTS_IDX (event_id),
  CONSTRAINT FK_MULE_EVENTS_ANNOTATIONS_MULE_EVENTS
  FOREIGN KEY (event_id) REFERENCES MULE_EVENTS (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE MULE_EVENTS_BUSINESS (
  id CHAR(36) NOT NULL,
  event_id CHAR(36) NOT NULL,
  business_key VARCHAR(30) NOT NULL,
  business_value VARCHAR(255) NULL,
  PRIMARY KEY (id),
  KEY FK_MULE_EVENTS_BUSINESS_IDX (event_id),
  CONSTRAINT FK_MULE_EVENTS_BUSINESS_MULE_EVENTS
  FOREIGN KEY (event_id) REFERENCES MULE_EVENTS (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

....

=== Configuration Example for MySQL

[source,yaml]
.DB Internal Handler Configuration
....
---
  mule.agent.tracking.handler.database:
    driver: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.61.128/mule
    user: root
    pass: test
....
