= DB Internal Handler

The DB Internal handler will store all the Event Notifications produced from the
Mule ESB flows in a configurable database.
You have to copy your JDBC .jar driver to the {MULE_HOME}/plugins/mule-agent-plugin/lib,
so the mule agent can load it to the classpath.

=== Configurable Fields


|===
|Field|Data Type|Description|Type|Default Value

|driver
|String
|Represents the JDBC driver to use to communicate with the database server.
|Required
|

|jdbcUrl
|String
|Represents the JDBC url to the database server.
|Required
|

|user
|String
|The username to connect to the database server.
|Optional
|blank

|pass
|String
|The password to connect to the database server.
|Optional
|blank

|table
|String
|Represents the name of the table in which the agent will store the events.
|Optional
|MULE_EVENTS

|===

=== Proposed Table Schema to Store the Events

As an example we show the configuration for storing the events on a MySQL database.

[source,sql]
....
CREATE TABLE MULE_EVENTS (
 	action VARCHAR(500) NULL,
 	application VARCHAR(500) NULL,
 	mule_message VARCHAR(500) NULL,
 	mule_message_id VARCHAR(36) NULL,
 	notification_type VARCHAR(500) NULL,
 	path VARCHAR(500) NULL,
 	resource_identifier VARCHAR(500) NULL,
 	timestamp BIGINT NULL,
 	source TEXT NULL
 )
....

=== Configuration Example for MySQL

[source,yaml]
.DB Internal Handler Configuration
....
---
  mule.agent.tracking.handler.database:
    driver: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.61.128/mule
    user: root
    pass: test
    table: mule
....